package rcsscommon

// ServerParams is an object containing all supported server parameters.
type ServerParams struct {
	// TODO: explain each server param behavior
	AudioCutDist              float64
	AutoMode                  bool
	BackDashRate              float64
	BackPasses                bool
	BallAccelMax              float64
	BallStuckArea             float64
	BallWeight                float64
	CatchBanCycle             int
	CatchProbability          float64
	CatchableAreaL            float64
	CatchableAreaW            float64
	CKickMargin               float64
	CLangAdviceWin            int64
	CLangDefineWin            int64
	CLangDelWin               int64
	CLangInfoWin              int64
	CLangMessDelay            int64
	CLangMessPerCycle         int64
	CLangMetaWin              int64
	CLangRuleWin              int64
	CLangWinSize              int64
	Coach                     bool
	CoachPort                 int64
	CoachWReferee             bool
	ConnectWait               int64
	ControlRadius             float64
	DashAngleStep             float64
	DashPowerRate             float64
	DropBallTime              int64
	EffortDec                 float64
	EffortDecThr              float64
	EffortInc                 float64
	EffortIncThr              float64
	EffortInit                float64
	EffortMin                 float64
	ExtraHalfTime             int64
	ExtraStamina              float64
	FixedTeamnameL            string
	FixedTeamnameR            string
	ForbidKickOffOffside      bool
	FoulCycles                int64
	FoulDetectProbability     float64
	FoulExponent              float64
	FreeKickFaults            int64
	FreeformSendPeriod        int64
	FreeformWaitPeriod        int64
	FullstateL                bool
	FullstateR                bool
	GameLogCompression        bool
	GameLogDated              bool
	GameLogDir                string
	GameLogFixed              bool
	GameLogFixedName          string
	GameLogVersion            int64
	GameLogging               bool
	GameOverWait              int64
	GoalWidth                 float64
	GoalieMaxMoves            int64
	GoldenGoal                bool
	HalfTime                  int64 // seconds
	HearDecay                 float64
	HearInc                   float64
	HearMax                   float64
	IllegalDefenseDistX       float64
	IllegalDefenseDuration    int64
	IllegalDefenseNumber      int64
	IllegalDefenseWidth       float64
	InertiaMoment             float64
	Keepaway                  bool
	KeepawayLength            float64
	KeepawayLogDated          bool
	KeepawayLogDir            string
	KeepawayLogFixed          bool
	KeepawayLogFixedName      string
	KeepawayLogging           bool
	KeepawayStart             int64
	KeepawayWidth             float64
	KickOffWait               int64
	KickPowerRate             float64
	KickRand                  float64
	KickRandFactorL           bool
	KickRandFactorR           bool
	KickableMargin            float64
	LandmarkFile              string
	LogDateFormat             string
	LogTimes                  bool
	MaxBackTacklePower        float64
	MaxDashAngle              float64
	MaxDashPower              float64
	MaxGoalKicks              int64
	MaxTacklePower            float64
	MaxMoment                 float64
	MaxNeckAng                float64
	MaxNeckMoment             float64
	MaxPower                  float64
	MinDashAngle              float64
	MinDashPower              float64
	MinMoment                 float64
	MinNeckAng                float64
	MinNeckMoment             float64
	MinPower                  float64
	NrExtraHalfs              int64
	NrNormalHalfs             int64
	OffsideActiveAreaSize     float64
	OffsideKickMargin         float64
	OnlineCoachPort           int64
	OldCoachHear              int64
	PenAllowMultKicks         bool
	PenBeforeSetupWait        int64
	PenCoachMovesPlayers      bool
	PenDistX                  float64
	PenMaxExtraKicks          int64
	PenMaxGoalieDistX         float64
	PenNrKicks                int64
	PenRandomWinner           bool
	PenReadyWait              int64
	PenSetupWait              int64
	PenTakenWait              int64
	PenaltyShootOuts          bool
	PlayerAccelMax            float64
	PlayerDecay               float64
	PlayerRand                float64
	PlayerSize                float64
	PlayerSpeedMax            float64
	PlayerSpeedMaxMin         float64
	PlayerWeight              float64
	PointToBan                int64
	PointToDuration           int64
	Port                      int64
	PRandFactorL              float64
	PRandFactorR              float64
	Profile                   int64
	ProperGoalKicks           int64
	QuantizeStep              float64
	QuantizeStepL             float64
	RecordMessages            bool
	RecoverDec                float64
	RecoverDecThr             float64
	RecoverInit               float64
	RecoverMin                float64
	RecvStep                  int64
	RedCardProbability        float64
	SayCoachCountMax          int64
	SayCoachMsgSize           int64
	SayMsgSize                int64
	SendComms                 int64
	SendStep                  int64
	SendViStep                int64
	SenseBodyStep             int64
	SideDashRate              float64
	SimulatorStep             int64 // in milliseconds
	SlowDownFactor            float64
	SlownessOnTopForLeftTeam  bool
	SlownessOnTopForRightTeam bool
	StaminaCapacity           float64
	StaminaIncMax             float64
	StaminaMax                float64
	StartGoalL                int64
	StartGoalR                int64
	StoppedBallVel            float64
	SynchMicroSleep           int64
	SynchMode                 bool
	SynchOffset               int64
	SynchSeeOffset            int64
	TackleBackDist            float64
	TackleCycles              int64
	TackleDist                float64
	TackleExponent            float64
	TacklePowerRate           float64
	TackleRandFactor          float64
	TackleWidth               float64
	TeamActuatorNoise         int64
	TeamLStart                string
	TeamRStart                string
	TextLogCompression        bool
	TextLogDated              bool
	TextLogDir                string
	TextLogFixed              bool
	TextLogFixedName          string
	TextLogging               bool
	UseOffside                bool
	Verbose                   bool
	VisibleAngle              float64
	VisibleDistance           float64
	WindAng                   float64
	WindDir                   float64
	WindForce                 float64
	WindNone                  bool
	WindRand                  float64
	WindRandom                float64
}

// Init initializes server params with default version 16.0.0 values
func (sp *ServerParams) Init() {
	*sp = ServerParams{
		AudioCutDist:              50,
		AutoMode:                  false,
		BackDashRate:              0.6,
		BackPasses:                true,
		BallAccelMax:              2.7,
		BallStuckArea:             3,
		BallWeight:                0.2,
		CatchBanCycle:             5,
		CatchProbability:          1,
		CatchableAreaL:            1.2,
		CatchableAreaW:            1,
		CKickMargin:               1,
		CLangAdviceWin:            1,
		CLangDefineWin:            1,
		CLangDelWin:               1,
		CLangInfoWin:              1,
		CLangMessDelay:            50,
		CLangMessPerCycle:         1,
		CLangMetaWin:              1,
		CLangRuleWin:              1,
		CLangWinSize:              300,
		Coach:                     false,
		CoachPort:                 6001,
		CoachWReferee:             false,
		ConnectWait:               300,
		ControlRadius:             2,
		DashAngleStep:             1,
		DashPowerRate:             0.006,
		DropBallTime:              100,
		EffortDec:                 0.005,
		EffortDecThr:              0.3,
		EffortInc:                 0.01,
		EffortIncThr:              0.6,
		EffortInit:                1,
		EffortMin:                 0.6,
		ExtraHalfTime:             100,
		ExtraStamina:              50,
		FixedTeamnameL:            "",
		FixedTeamnameR:            "",
		ForbidKickOffOffside:      true,
		FoulCycles:                5,
		FoulDetectProbability:     0.5,
		FoulExponent:              10,
		FreeKickFaults:            1,
		FreeformSendPeriod:        20,
		FreeformWaitPeriod:        600,
		FullstateL:                false,
		FullstateR:                false,
		GameLogCompression:        false,
		GameLogDated:              true,
		GameLogDir:                "/root/logs",
		GameLogFixed:              false,
		GameLogFixedName:          "rcssserver",
		GameLogVersion:            5,
		GameLogging:               true,
		GameOverWait:              100,
		GoalWidth:                 14.02,
		GoalieMaxMoves:            2,
		GoldenGoal:                false,
		HalfTime:                  300,
		HearDecay:                 1,
		HearInc:                   1,
		HearMax:                   1,
		IllegalDefenseDistX:       16.5,
		IllegalDefenseDuration:    20,
		IllegalDefenseNumber:      0,
		IllegalDefenseWidth:       40.32,
		InertiaMoment:             5,
		Keepaway:                  false,
		KeepawayLength:            20,
		KeepawayLogDated:          true,
		KeepawayLogDir:            "./",
		KeepawayLogFixed:          false,
		KeepawayLogFixedName:      "rcssserver",
		KeepawayLogging:           true,
		KeepawayStart:             -1,
		KeepawayWidth:             20,
		KickOffWait:               100,
		KickPowerRate:             0.027,
		KickRand:                  0.1,
		KickRandFactorL:           true,
		KickRandFactorR:           true,
		KickableMargin:            0.7,
		LandmarkFile:              "~/.rcssserver-landmark.xml",
		LogDateFormat:             "%Y%m%d%H%M%S-",
		LogTimes:                  false,
		MaxBackTacklePower:        100,
		MaxDashAngle:              180,
		MaxDashPower:              100,
		MaxGoalKicks:              3,
		MaxTacklePower:            100,
		MaxMoment:                 180,
		MaxNeckAng:                90,
		MaxNeckMoment:             180,
		MaxPower:                  100,
		MinDashAngle:              -180,
		MinDashPower:              -100,
		MinMoment:                 -180,
		MinNeckAng:                -90,
		MinNeckMoment:             -180,
		MinPower:                  -100,
		NrExtraHalfs:              2,
		NrNormalHalfs:             2,
		OffsideActiveAreaSize:     2.5,
		OffsideKickMargin:         9.15,
		OnlineCoachPort:           6002,
		OldCoachHear:              0,
		PenAllowMultKicks:         true,
		PenBeforeSetupWait:        10,
		PenCoachMovesPlayers:      true,
		PenDistX:                  42.5,
		PenMaxExtraKicks:          5,
		PenMaxGoalieDistX:         14,
		PenNrKicks:                5,
		PenRandomWinner:           false,
		PenReadyWait:              10,
		PenSetupWait:              70,
		PenTakenWait:              150,
		PenaltyShootOuts:          true,
		PlayerAccelMax:            1,
		PlayerDecay:               0.4,
		PlayerRand:                0.1,
		PlayerSize:                0.3,
		PlayerSpeedMax:            1.05,
		PlayerSpeedMaxMin:         0.75,
		PlayerWeight:              60,
		PointToBan:                5,
		PointToDuration:           20,
		Port:                      6000,
		PRandFactorL:              1,
		PRandFactorR:              1,
		Profile:                   0,
		ProperGoalKicks:           0,
		QuantizeStep:              0.1,
		QuantizeStepL:             0.01,
		RecordMessages:            false,
		RecoverDec:                0.002,
		RecoverDecThr:             0.3,
		RecoverInit:               1,
		RecoverMin:                0.5,
		RecvStep:                  10,
		RedCardProbability:        0,
		SayCoachCountMax:          128,
		SayCoachMsgSize:           128,
		SayMsgSize:                10,
		SendComms:                 0,
		SendStep:                  150,
		SendViStep:                100,
		SenseBodyStep:             100,
		SideDashRate:              0.4,
		SimulatorStep:             100,
		SlowDownFactor:            1,
		SlownessOnTopForLeftTeam:  true,
		SlownessOnTopForRightTeam: true,
		StaminaCapacity:           130600,
		StaminaIncMax:             45,
		StaminaMax:                8000,
		StartGoalL:                0,
		StartGoalR:                0,
		StoppedBallVel:            0.01,
		SynchMicroSleep:           1,
		SynchMode:                 false,
		SynchOffset:               60,
		SynchSeeOffset:            0,
		TackleBackDist:            0,
		TackleCycles:              10,
		TackleDist:                2,
		TackleExponent:            6,
		TacklePowerRate:           0.027,
		TackleRandFactor:          2,
		TackleWidth:               1.25,
		TeamActuatorNoise:         0,
		TeamLStart:                "",
		TeamRStart:                "",
		TextLogCompression:        false,
		TextLogDated:              true,
		TextLogDir:                "/root/logs",
		TextLogFixed:              false,
		TextLogFixedName:          "rcssserver",
		TextLogging:               true,
		UseOffside:                true,
		Verbose:                   false,
		VisibleAngle:              90,
		VisibleDistance:           3,
		WindAng:                   0,
		WindDir:                   0,
		WindForce:                 0,
		WindNone:                  false,
		WindRand:                  0,
		WindRandom:                0,
	}
}

// TODO: centralize server params lexer and parser for both player and trainer with methods to update this struct
