package parser

import "github.com/rcssggb/ggb-lib/rcsscommon"

var flagMap = map[string]rcsscommon.FlagID{
	"f c":       rcsscommon.FlagCenter,
	"f c t":     rcsscommon.FlagCenterTop,
	"f c b":     rcsscommon.FlagCenterBot,
	"g l":       rcsscommon.FlagLeftGoal,
	"f g l t":   rcsscommon.FlagLeftGoalTop,
	"f g l b":   rcsscommon.FlagLeftGoalBot,
	"g r":       rcsscommon.FlagRightGoal,
	"f g r t":   rcsscommon.FlagRightGoalTop,
	"f g r b":   rcsscommon.FlagRightGoalBot,
	"f p l c":   rcsscommon.FlagLeftPenaltyCenter,
	"f p l t":   rcsscommon.FlagLeftPenaltyTop,
	"f p l b":   rcsscommon.FlagLeftPenaltyBot,
	"f p r c":   rcsscommon.FlagRightPenaltyCenter,
	"f p r t":   rcsscommon.FlagRightPenaltyTop,
	"f p r b":   rcsscommon.FlagRightPenaltyBot,
	"f l t":     rcsscommon.FlagLeftTop,
	"f l b":     rcsscommon.FlagLeftBot,
	"f r t":     rcsscommon.FlagRightTop,
	"f r b":     rcsscommon.FlagRightBot,
	"f t l 50":  rcsscommon.FlagTopLeft50,
	"f t l 40":  rcsscommon.FlagTopLeft40,
	"f t l 30":  rcsscommon.FlagTopLeft30,
	"f t l 20":  rcsscommon.FlagTopLeft20,
	"f t l 10":  rcsscommon.FlagTopLeft10,
	"f t 0":     rcsscommon.FlagTop0,
	"f t r 10":  rcsscommon.FlagTopRight10,
	"f t r 20":  rcsscommon.FlagTopRight20,
	"f t r 30":  rcsscommon.FlagTopRight30,
	"f t r 40":  rcsscommon.FlagTopRight40,
	"f t r 50":  rcsscommon.FlagTopRight50,
	"f b l 50":  rcsscommon.FlagBotLeft50,
	"f b l 40":  rcsscommon.FlagBotLeft40,
	"f b l 30":  rcsscommon.FlagBotLeft30,
	"f b l 20":  rcsscommon.FlagBotLeft20,
	"f b l 10":  rcsscommon.FlagBotLeft10,
	"f b 0":     rcsscommon.FlagBot0,
	"f b r 10":  rcsscommon.FlagBotRight10,
	"f b r 20":  rcsscommon.FlagBotRight20,
	"f b r 30":  rcsscommon.FlagBotRight30,
	"f b r 40":  rcsscommon.FlagBotRight40,
	"f b r 50":  rcsscommon.FlagBotRight50,
	"f l t 30":  rcsscommon.FlagLeftTop30,
	"f l t 20":  rcsscommon.FlagLeftTop20,
	"f l t 10":  rcsscommon.FlagLeftTop10,
	"f l 0":     rcsscommon.FlagLeft0,
	"f l b 10":  rcsscommon.FlagLeftBot10,
	"f l b 20":  rcsscommon.FlagLeftBot20,
	"f l b 30":  rcsscommon.FlagLeftBot30,
	"f r t 30":  rcsscommon.FlagRightTop30,
	"f r t 20":  rcsscommon.FlagRightTop20,
	"f r t 10":  rcsscommon.FlagRightTop10,
	"f r 0":     rcsscommon.FlagRight0,
	"f r bg 10": rcsscommon.FlagRightBot10,
	"f r bg 20": rcsscommon.FlagRightBot20,
	"f r bg 30": rcsscommon.FlagRightBot30,
}
