package parser

var flagMap = map[string]FlagID{
	"f c":      CenterFlag,
	"f c t":    CenterTopFlag,
	"f c b":    CenterBotFlag,
	"g l":      LeftGoalFlag,
	"f g l t":  LeftGoalTopFlag,
	"f g l b":  LeftGoalBotFlag,
	"g r":      RightGoalFlag,
	"f g r t":  RightGoalTopFlag,
	"f g r b":  RightGoalBotFlag,
	"f p l c":  LeftPenaltyCenterFlag,
	"f p l t":  LeftPenaltyTopFlag,
	"f p l b":  LeftPenaltyBotFlag,
	"f p r c":  RightPenaltyCenterFlag,
	"f p r t":  RightPenaltyTopFlag,
	"f p r b":  RightPenaltyBotFlag,
	"f l t":    LeftTopFlag,
	"f l b":    LeftBotFlag,
	"f r t":    RightTopFlag,
	"f r b":    RightBotFlag,
	"f t l 50": TopLeft50Flag,
	"f t l 40": TopLeft40Flag,
	"f t l 30": TopLeft30Flag,
	"f t l 20": TopLeft20Flag,
	"f t l 10": TopLeft10Flag,
	"f t 0":    Top0Flag,
	"f t r 10": TopRight10Flag,
	"f t r 20": TopRight20Flag,
	"f t r 30": TopRight30Flag,
	"f t r 40": TopRight40Flag,
	"f t r 50": TopRight50Flag,
	"f b l 50": BotLeft50Flag,
	"f b l 40": BotLeft40Flag,
	"f b l 30": BotLeft30Flag,
	"f b l 20": BotLeft20Flag,
	"f b l 10": BotLeft10Flag,
	"f b 0":    Bot0Flag,
	"f b r 10": BotRight10Flag,
	"f b r 20": BotRight20Flag,
	"f b r 30": BotRight30Flag,
	"f b r 40": BotRight40Flag,
	"f b r 50": BotRight50Flag,
	"f l t 30": LeftTop30Flag,
	"f l t 20": LeftTop20Flag,
	"f l t 10": LeftTop10Flag,
	"f l 0":    Left0Flag,
	"f l b 10": LeftBot10Flag,
	"f l b 20": LeftBot20Flag,
	"f l b 30": LeftBot30Flag,
	"f r t 30": RightTop30Flag,
	"f r t 20": RightTop20Flag,
	"f r t 10": RightTop10Flag,
	"f r 0":    Right0Flag,
	"f r bg 10": RightBot10Flag,
	"f r bg 20": RightBot20Flag,
	"f r bg 30": RightBot30Flag,
}
